templateDir: templates/python
additionalProperties:
  packageName: ledgerclient
  infoName: Numary ledger Client
  infoEmail: support@numary.com
  PYPI_SECRET: "${{ secrets.PYPI_SECRET }}"

files:
  Taskfile.yml.mustache:
    destinationFilename: Taskfile.yml
  .github/workflows/release.yml.mustache:
    destinationFilename: .github/workflows/release.yml
