services:
  ledger:
    image: golang:1.16-alpine
    entrypoint: go run main.go server start
    volumes:
      - .:/src
    working_dir: /src
    environment:
      CGO_ENABLED: 0
      NUMARY_DEBUG: "true"
      NUMARY_OTEL_TRACES: "true"
      NUMARY_OTEL_TRACES_EXPORTER: jaeger
      NUMARY_OTEL_TRACES_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      NUMARY_OTEL_TRACES_EXPORTER_JAEGER_INSECURE: "true"
      NUMARY_OTEL_METRICS: "false"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports:
      - 16686:16686
