# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/stack.formance.com_stacks.yaml
- bases/components.formance.com_auths.yaml
- bases/components.formance.com_ledgers.yaml
- bases/components.formance.com_payments.yaml
- bases/components.formance.com_searches.yaml
- bases/components.formance.com_controls.yaml
- bases/components.formance.com_wallets.yaml
- bases/components.formance.com_counterparties.yaml
- bases/auth.components.formance.com_clients.yaml
- bases/auth.components.formance.com_scopes.yaml
- bases/benthos.components.formance.com_servers.yaml
- bases/benthos.components.formance.com_streams.yaml
- bases/stack.formance.com_configurations.yaml
- bases/components.formance.com_webhooks.yaml
- bases/stack.formance.com_versions.yaml
- bases/components.formance.com_orchestrations.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
#- patches/webhook_in_stack_stacks.yaml
#- patches/cainjection_in_stack_stacks.yaml
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_licenses.yaml
#- patches/webhook_in_ledgers.yaml
#- patches/webhook_in_payments.yaml
#- patches/webhook_in_searches.yaml
#- patches/webhook_in_controls.yaml
#- patches/webhook_in_scopes.yaml
#- patches/webhook_in_auth.components_clients.yaml
#- patches/webhook_in_auth.components_scopes.yaml
#- patches/webhook_in_components_auths.yaml
#- patches/webhook_in_servers.yaml
#- patches/webhook_in_streams.yaml
- patches/webhook_in_stack_configurations.yaml
#- patches/webhook_in_webhooks.yaml
#- patches/webhook_in_versions.yaml
- patches/webhook_in_stack_stacks.yaml
#- patches/webhook_in_orchestrations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_licenses.yaml
#- patches/cainjection_in_auths.yaml
#- patches/cainjection_in_ledgers.yaml
#- patches/cainjection_in_payments.yaml
#- patches/cainjection_in_searches.yaml
#- patches/cainjection_in_controls.yaml
#- patches/cainjection_in_oauths.yaml
#- patches/cainjection_in_scopes.yaml
#- patches/cainjection_in_servers.yaml
#- patches/cainjection_in_streams.yaml
- patches/cainjection_in_stack_configurations.yaml
#- patches/cainjection_in_webhooks.yaml
#- patches/cainjection_in_versions.yaml
- patches/cainjection_in_stack_stacks.yaml
#- patches/cainjection_in_orchestrations.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
