exclude: (client|internal/grpc)
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: .cloud
  - id: check-added-large-files
- repo: https://github.com/formancehq/pre-commit-hooks
  rev: dd079f7c30ad72446d615f55a000d4f875e79633
  hooks:
  - id: gogenerate
    files: pkg/server/openapi.yaml
  - id: gomodtidy
  - id: goimports
  - id: gofmt
  - id: golangci-lint
#  - id: gotests
  - id: commitlint
