# templateDir: templates/java
# files:
#   Taskfile.yml.mustache:
#     destinationFilename: Taskfile.yml
additionalProperties:
  invokerPackage: com.formance.formance
  apiPackage: com.formance.formance.api
  modelPackage: com.formance.formance.model
  groupId: com.formance
  artifactId: formance
  artifactDescription: Ledger Java Client
  artifactUrl: https://github.com/formancehq/formance-sdk-java
  scmConnection: scm:git:git@github.com/formancehq/formance-sdk-java.git
  scmDeveloperConnection: scm:git:git@github.com/formancehq/formance-sdk-java.git
  scmUrl: https://github.com/formancehq/formance-sdk-java
  developerEmail: support@formance.com
  developerName: Ledger Java Client Contributors
  developerOrganization: Formance
  developerOrganizationUrl: https://formance.com
  library: retrofit2
  openApiNullable: false
  licenseName: MIT License
  licenseUrl: http://www.opensource.org/licenses/mit-license.php
  gpg_private_key: '${{ secrets.GPG_SIGNING_KEY }}'
  gpg_passphrase: '${{ secrets.GPG_PASSPHRASE }}'
  nexus_username: '${{ secrets.OSSRH_USERNAME }}'
  nexus_password: '${{ secrets.OSSRH_PASSWORD }}'
  hideGenerationTimestamp: true

inlineSchemaNameMappings:
  getAccount_200_response: GetAccountResponse
  listAccounts_200_response: ListAccountsResponse
  listAccounts_200_response_cursor: ListAccountsResponseCursor
  listTransactions_200_response: ListTransactionsResponse
  listTransactions_200_response_cursor: ListTransactionsResponseCursor
