clients:
  - id: testing
    secrets:
    - testing
    name: testing
  - id: control
    secrets:
      - mysupersecret
    redirectUris:
      - http://localhost:3000/auth/login
      - http://localhost/auth/login
      - https://oauth.pstmn.io/v1/callback
    name: control
    postLogoutRedirectUris:
      - http://localhost:3000/auth/destroy
      - http://localhost/auth/destroy
