on:
  release:
    types: [prereleased, released]

name: Release - OpenAPI
defaults:
  run:
    working-directory: "./openapi"
jobs:
  Build:
    name: 'SDK Build & Publish'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ go, php, python, typescript-node, java ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: ./openapi/yarn.lock
      - run: yarn install
      - run: task sdk:build
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          repository: formancehq/formance-sdk-${{ matrix.sdk }}
          path: ./openapi/sdk/sdks/${{ matrix.sdk }}
      - name: Build SDK for Release
        run: task sdk:generate VERSION=${{ github.event.release.tag_name }} -- ${{ matrix.sdk }}
      - name: Push commit to SDK Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: Upgrade Release to ${{ github.event.release.tag_name }}"
          create_branch: true
          branch: release/${{ github.event.release.tag_name }}
          repository: ./openapi/sdk/sdks/${{ matrix.sdk }}
          commit_user_name: NumaryBot
          commit_user_email: support@formance.com
      - name: Create PR
        run: gh pr create --base main --head release/${{ github.event.release.tag_name }} --title "Upgrade to ${{ github.event.release.tag_name }}" --body "Upgrade to ${{ github.event.release.tag_name }}"
        working-directory: ./openapi/sdk/sdks/${{ matrix.sdk }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  Publish:
    name: 'Publish OpenAPI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: ./openapi/yarn.lock
      - run: yarn install
      - run: task sdk:build VERSION=${{ github.event.release.tag_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./openapi/sdk/generate.json