name: SDK Generate
on:
  workflow_call:
    secrets:
      NUMARY_GITHUB_TOKEN:
        required: true
        description: GitHub token with access to the repo

jobs:
  Sdk:
    name: 'Generate SDK'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ go, php, python, typescript-node, java ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          ref: ${{ inputs.VERSION }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          repository: formancehq/numary-sdk-${{ matrix.sdk }}
          path: sdks/${{ matrix.sdk }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Launch Generate
        run: task sdk:generate VERSION=main -- ${{ matrix.sdk }}
