name: GoReleaser Release
on:
  workflow_call:
    secrets:
      NUMARY_GITHUB_TOKEN:
        required: true
        description: GitHub token with access to the repo
      FURY_TOKEN:
        required: true
        description: Fury token for the OSS repo

jobs:
  goreleaser:
    name: GoReleaser Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: fetch numary control
        uses: actions/download-artifact@v2
        with:
          name: control-dist
          path: cmd/control/
      - run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu gcc-mingw-w64 -y
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Run GoReleaser for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
      - name: Run GoReleaser for MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f .goreleaser-darwin.yml --rm-dist
      - uses: actions/cache@v2
        with:
          path: |
            ./dist/*.deb
            ./dist/*.rpm
            ./dist/*.apk
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}-${{ hashFiles('**/go.sum') }}
